inherit: true
checks:
    php: true
filter:
    excluded_paths:
        - 'composer.lock'
        - 'vendor/*'
        - 'Tests/*'
build_failure_conditions:
    - 'elements.rating(< D).new.exists'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.01)'
build:
    environment:
        php: '7.1'
        mysql: false
        memcached: false
        node: false
        mongodb: false
        redis: false
        postgresql: false
        elasticsearch: false
        neo4j: false
        rabbitmq: false
        variables:
            SYMFONY_DEPRECATIONS_HELPER: 'weak'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
