inherit: true
checks:
    php: true
filter:
    excluded_paths:
        - 'composer.lock'
        - 'vendor/*'
        - 'Tests/*'
build:
    environment:
        php: '7.0.8'
    tests:
        override:
            -
                command: 'SYMFONY_DEPRECATIONS_HELPER=weak phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
