language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - composer require --no-update roave/security-advisories:dev-master
  - composer install -n --no-progress

before_script:
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/phpunit -v

after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $TRAVIS_PHP_VERSION == "7.0" ]]; then sh generate-api.sh; fi;'

notifications:
  email: false
