language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer require --no-update roave/security-advisories:dev-master

jobs:
  include:
    - name: Default Installation
      install:
        - composer install -n --no-progress

      php:
        - 7.1
        - 7.2

    - name: Minimum Requirements
      install:
        - composer update -n --no-progress --prefer-lowest

      php:
        - 7.1
        - 7.2

before_script:
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix

script:
  - vendor/bin/phpunit -v

notifications:
  email: false
